name: dev-python
on:
  push:
    branches: [ main ]
    paths:
      - 'dockerfiles/dev-python/**'  # 监控指定目录变更触发构建
  workflow_dispatch:
    inputs:
      dockerfiles:
        description: '要构建的 Dockerfile 路径（逗号分隔）'
        required: false

jobs:
  multi-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dockerfile: 
          - { path: "dockerfiles/dev-python/Dockerfile", image: "${{ secrets.ALI_DOCKERHUB_REGISTRY }}/oatelauser/dev-python" }
#          - { path: "dockerfiles/dev-cuda-pytorch-python/Dockerfile", image: "oatelauser/dev-python" }
    steps:
      - name: Before freeing up disk space
        run: |
          echo "Before freeing up disk space"
          echo "=============================================================================="
          df -hT
          echo "=============================================================================="

      # 增加可用磁盘空间
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 2048
          swap-size-mb: 128
          remove-dotnet: 'true'
          remove-haskell: 'true'
          # 如果空间还是不够用，可以把以下开启，清理出更多空间
          # remove-android: 'true'
          # remove-codeql: 'true'
          build-mount-path: '/var/lib/docker/'

      - name: Restart docker
        run: sudo service docker restart

      - name: Free up disk space complete
        run: |
          echo "Free up disk space complete"
          echo "=============================================================================="
          df -hT
          echo "=============================================================================="
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Aliyun Docker Hub
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.ALI_DOCKERHUB_REGISTRY }}
          username: ${{ secrets.ALI_DOCKERHUB_USERNAME }}
          password: ${{ secrets.ALI_DOCKERHUB_TOKEN }}

      - name: Build & Push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ${{ matrix.dockerfile.path }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ matrix.dockerfile.image }}:3.12