name: Multi-Docker Build & Push
on:
  push:
    branches: [ main ]
    paths:
      - 'dockerfiles/**'  # 监控指定目录变更触发构建
  workflow_dispatch:
    inputs:
      dockerfiles:
        description: '要构建的 Dockerfile 路径（逗号分隔）'
        required: false

jobs:
  multi-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dockerfile: 
          - { path: "dockerfiles/dev-cuda-python/Dockerfile", image: "dev-cuda-python" }
          - { path: "dockerfiles/dev-cuda-pytorch-python/Dockerfile", image: "dev-cuda-pytorch-python" }
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ${{ matrix.dockerfile.path }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ matrix.dockerfile.image }}:latest
            ${{ matrix.dockerfile.image }}:${{ github.sha }}